export const STORE_API_KEY = process.env.REACT_APP_STORE_API_KEY;
export const STORE_API_URL = "https://api.chec.io/";

export const testApi=
[
 {
     "id": "prod_Op1YoVDDyglXLv",
     "created": 1669157059,
     "updated": 1669169005,
     "active": true,
     "permalink": "3db3W1",
     "name": "Canon EOS R6 Mark II Mirrorless Camera",
     "description": "<p><strong>Key Features</strong></p><ul><li><p>24.2MP Full-Frame CMOS Sensor</p></li><li><p>4K60 10-Bit Internal Video, C-Log 3</p></li><li><p>External 6K ProRes RAW Recording</p></li><li><p>Dual Pixel CMOS AF II.</p></li></ul>",
     "price": {
         "raw": 2499,
         "formatted": "2,499.00",
         "formatted_with_symbol": "$2,499.00",
         "formatted_with_code": "2,499.00 USD"
     },
     "inventory": {
         "managed": true,
         "available": 10
     },
     "sku": "5666C002",
     "sort_order": 0,
     "seo": {
         "title": null,
         "description": null
     },
     "thank_you_url": null,
     "meta": null,
     "conditionals": {
         "is_active": true,
         "is_tax_exempt": false,
         "is_pay_what_you_want": false,
         "is_inventory_managed": true,
         "is_sold_out": false,
         "has_digital_delivery": false,
         "has_physical_delivery": false,
         "has_images": true,
         "collects_fullname": false,
         "collects_shipping_address": false,
         "collects_billing_address": false,
         "collects_extra_fields": false
     },
     "is": {
         "active": true,
         "tax_exempt": false,
         "pay_what_you_want": false,
         "inventory_managed": true,
         "sold_out": false
     },
     "has": {
         "digital_delivery": false,
         "physical_delivery": false,
         "images": true
     },
     "collects": {
         "fullname": false,
         "shipping_address": false,
         "billing_address": false,
         "extra_fields": false
     },
     "checkout_url": {
         "checkout": "https://checkout.chec.io/3db3W1?checkout=true",
         "display": "https://checkout.chec.io/3db3W1"
     },
     "categories": [
         {
             "id": "cat_ypbroELNXw8n4e",
             "slug": "full-frame",
             "name": "Full Frame"
         },
         {
             "id": "cat_O3bR5X24Qwnzdj",
             "slug": "mirrorless",
             "name": "Mirrorless"
         }
     ],
     "image": {
         "id": "ast_eN1ql9jA3zwz3y",
         "url": "https://cdn.chec.io/merchants/48635/assets/FDmYVLpxlDqKbxcq|CanonEOSR6.jpg",
         "description": null,
         "is_image": true,
         "filename": "CanonEOSR6.jpg",
         "file_size": 114330,
         "file_extension": "jpg",
         "image_dimensions": {
             "width": 1000,
             "height": 1000
         },
         "meta": [],
         "created_at": 1669157015,
         "updated_at": 1669157016
     },
     "statistics": {
         "orders": 0,
         "sales": {
             "raw": 0,
             "formatted": "0.00",
             "formatted_with_symbol": "$0.00",
             "formatted_with_code": "0.00 USD"
         }
     }
 },
 {
     "id": "prod_zkK6oLQQ2E5Xn0",
     "created": 1669158203,
     "updated": 1669158455,
     "active": true,
     "permalink": "fy6fFO",
     "name": "Sony a7R V Mirrorless Camera",
     "description": "<p><strong>Key Features</strong></p><ul><li><p>61MP Full-Frame Exmor R BSI CMOS Sensor</p></li><li><p>BIONZ XR & AI Processing Unit</p></li><li><p>AI-Based Real-Time Tracking AF System</p></li><li><p>8K 24p, 4K 60p, FHD 120p 10-Bit Video</p></li></ul>",
     "price": {
         "raw": 3898,
         "formatted": "3,898.00",
         "formatted_with_symbol": "$3,898.00",
         "formatted_with_code": "3,898.00 USD"
     },
     "inventory": {
         "managed": true,
         "available": 4
     },
     "sku": "ILCE7RM5/B",
     "sort_order": 0,
     "seo": {
         "title": null,
         "description": null
     },
     "thank_you_url": null,
     "meta": null,
     "conditionals": {
         "is_active": true,
         "is_tax_exempt": false,
         "is_pay_what_you_want": false,
         "is_inventory_managed": true,
         "is_sold_out": false,
         "has_digital_delivery": false,
         "has_physical_delivery": false,
         "has_images": true,
         "collects_fullname": false,
         "collects_shipping_address": false,
         "collects_billing_address": false,
         "collects_extra_fields": false
     },
     "is": {
         "active": true,
         "tax_exempt": false,
         "pay_what_you_want": false,
         "inventory_managed": true,
         "sold_out": false
     },
     "has": {
         "digital_delivery": false,
         "physical_delivery": false,
         "images": true
     },
     "collects": {
         "fullname": false,
         "shipping_address": false,
         "billing_address": false,
         "extra_fields": false
     },
     "checkout_url": {
         "checkout": "https://checkout.chec.io/fy6fFO?checkout=true",
         "display": "https://checkout.chec.io/fy6fFO"
     },
     "categories": [
         {
             "id": "cat_ypbroELNXw8n4e",
             "slug": "full-frame",
             "name": "Full Frame"
         },
         {
             "id": "cat_O3bR5X24Qwnzdj",
             "slug": "mirrorless",
             "name": "Mirrorless"
         }
     ],
     "image": {
         "id": "ast_7ZAMo1V9015NJ4",
         "url": "https://cdn.chec.io/merchants/48635/assets/vFBkdIF5Id2Ysjy4|Sonya7RV.jpg",
         "description": null,
         "is_image": true,
         "filename": "Sonya7RV.jpg",
         "file_size": 53216,
         "file_extension": "jpg",
         "image_dimensions": {
             "width": 500,
             "height": 500
         },
         "meta": [],
         "created_at": 1669158292,
         "updated_at": 1669158292
     },
     "statistics": {
         "orders": 0,
         "sales": {
             "raw": 0,
             "formatted": "0.00",
             "formatted_with_symbol": "$0.00",
             "formatted_with_code": "0.00 USD"
         }
     }
 },
 {
     "id": "prod_AYrQlWDDqxwnbR",
     "created": 1669170031,
     "updated": 1669170072,
     "active": true,
     "permalink": "4xG8G3",
     "name": "Nikon D6 DSLR Camera",
     "description": "<p><strong>Key Features</strong></p><ul><li><p>24.3MP FX-Format CMOS Sensor</p></li><li><p>EXPEED 4 Image Processor</p></li><li><p>3.2\" 1,229k-Dot RGBW Tilting LCD Monitor</p></li><li><p>Full HD 1080p Video Recording at 60 fps</p></li></ul>",
     "price": {
         "raw": 6496.95,
         "formatted": "6,496.95",
         "formatted_with_symbol": "$6,496.95",
         "formatted_with_code": "6,496.95 USD"
     },
     "inventory": {
         "managed": true,
         "available": 3
     },
     "sku": "1624",
     "sort_order": 0,
     "seo": {
         "title": null,
         "description": null
     },
     "thank_you_url": null,
     "meta": null,
     "conditionals": {
         "is_active": true,
         "is_tax_exempt": false,
         "is_pay_what_you_want": false,
         "is_inventory_managed": true,
         "is_sold_out": false,
         "has_digital_delivery": false,
         "has_physical_delivery": false,
         "has_images": true,
         "collects_fullname": false,
         "collects_shipping_address": false,
         "collects_billing_address": false,
         "collects_extra_fields": false
     },
     "is": {
         "active": true,
         "tax_exempt": false,
         "pay_what_you_want": false,
         "inventory_managed": true,
         "sold_out": false
     },
     "has": {
         "digital_delivery": false,
         "physical_delivery": false,
         "images": true
     },
     "collects": {
         "fullname": false,
         "shipping_address": false,
         "billing_address": false,
         "extra_fields": false
     },
     "checkout_url": {
         "checkout": "https://checkout.chec.io/4xG8G3?checkout=true",
         "display": "https://checkout.chec.io/4xG8G3"
     },
     "categories": [
         {
             "id": "cat_ypbroELNXw8n4e",
             "slug": "full-frame",
             "name": "Full Frame"
         },
         {
             "id": "cat_Op1YoVynMwXLv9",
             "slug": "nikon",
             "name": "Nikon"
         }
     ],
     "image": {
         "id": "ast_8XO3wpQvzOoYAz",
         "url": "https://cdn.chec.io/merchants/48635/assets/7ZDjENmf35VRFdvY|NikonD6.jpg",
         "description": null,
         "is_image": true,
         "filename": "NikonD6.jpg",
         "file_size": 141727,
         "file_extension": "jpg",
         "image_dimensions": {
             "width": 1000,
             "height": 1000
         },
         "meta": [],
         "created_at": 1669170028,
         "updated_at": 1669170030
     },
     "statistics": {
         "orders": 0,
         "sales": {
             "raw": 0,
             "formatted": "0.00",
             "formatted_with_symbol": "$0.00",
             "formatted_with_code": "0.00 USD"
         }
     }
 },
 {
     "id": "prod_ypbroEyymmo8n4",
     "created": 1669170620,
     "updated": 1669170620,
     "active": true,
     "permalink": "LVIBKo",
     "name": "Canon EOS 6D Mark II DSLR Camera",
     "description": "<p><strong>Key Features</strong></p><ul><li><p>26.2MP Full-Frame CMOS Sensor</p></li><li><p>DIGIC 7 Image Processor</p></li><li><p>45-Point All-Cross Type AF System</p></li><li><p>Full HD Video at 60 fps; Digital IS</p></li></ul>",
     "price": {
         "raw": 2188.99,
         "formatted": "2,188.99",
         "formatted_with_symbol": "$2,188.99",
         "formatted_with_code": "2,188.99 USD"
     },
     "inventory": {
         "managed": true,
         "available": 17
     },
     "sku": "1897C009",
     "sort_order": 0,
     "seo": {
         "title": null,
         "description": null
     },
     "thank_you_url": null,
     "meta": null,
     "conditionals": {
         "is_active": true,
         "is_tax_exempt": false,
         "is_pay_what_you_want": false,
         "is_inventory_managed": true,
         "is_sold_out": false,
         "has_digital_delivery": false,
         "has_physical_delivery": false,
         "has_images": true,
         "collects_fullname": false,
         "collects_shipping_address": false,
         "collects_billing_address": false,
         "collects_extra_fields": false
     },
     "is": {
         "active": true,
         "tax_exempt": false,
         "pay_what_you_want": false,
         "inventory_managed": true,
         "sold_out": false
     },
     "has": {
         "digital_delivery": false,
         "physical_delivery": false,
         "images": true
     },
     "collects": {
         "fullname": false,
         "shipping_address": false,
         "billing_address": false,
         "extra_fields": false
     },
     "checkout_url": {
         "checkout": "https://checkout.chec.io/LVIBKo?checkout=true",
         "display": "https://checkout.chec.io/LVIBKo"
     },
     "categories": [
         {
             "id": "cat_0egY5eLn9o3QnA",
             "slug": "canon",
             "name": "Canon"
         },
         {
             "id": "cat_ypbroELNXw8n4e",
             "slug": "full-frame",
             "name": "Full Frame"
         }
     ],
     "image": {
         "id": "ast_4WJvlKVQve5bYV",
         "url": "https://cdn.chec.io/merchants/48635/assets/b5UbzkRQI3ETKIWC|CanonEOS6DDSLR.jpg",
         "description": null,
         "is_image": true,
         "filename": "CanonEOS6DDSLR.jpg",
         "file_size": 165217,
         "file_extension": "jpg",
         "image_dimensions": {
             "width": 1000,
             "height": 1000
         },
         "meta": [],
         "created_at": 1669170603,
         "updated_at": 1669170604
     },
     "statistics": {
         "orders": 0,
         "sales": {
             "raw": 0,
             "formatted": "0.00",
             "formatted_with_symbol": "$0.00",
             "formatted_with_code": "0.00 USD"
         }
     }
 }
]

export const QUANTITY_ARR = [];
for (let i = 1; i <= 20; i++) {
  QUANTITY_ARR.push([i]);
}

const cityNames = [
    "Aberdeen",
    "Abilene",
    "Akron",
    "Albany",
    "Albuquerque",
    "Alexandria",
    "Allentown",
    "Amarillo",
    "Anaheim",
    "Anchorage",
    "Ann Arbor",
    "Antioch",
    "Apple Valley",
    "Appleton",
    "Arlington",
    "Arvada",
    "Asheville",
    "Athens",
    "Atlanta",
    "Atlantic City",
    "Augusta",
    "Aurora",
    "Austin",
    "Bakersfield",
    "Baltimore",
    "Barnstable",
    "Baton Rouge",
    "Beaumont",
    "Bel Air",
    "Bellevue",
    "Berkeley",
    "Bethlehem",
    "Billings",
    "Birmingham",
    "Bloomington",
    "Boise",
    "Boise City",
    "Bonita Springs",
    "Boston",
    "Boulder",
    "Bradenton",
    "Bremerton",
    "Bridgeport",
    "Brighton",
    "Brownsville",
    "Bryan",
    "Buffalo",
    "Burbank",
    "Burlington",
    "Cambridge",
    "Canton",
    "Cape Coral",
    "Carrollton",
    "Cary",
    "Cathedral City",
    "Cedar Rapids",
    "Champaign",
    "Chandler",
    "Charleston",
    "Charlotte",
    "Chattanooga",
    "Chesapeake",
    "Chicago",
    "Chula Vista",
    "Cincinnati",
    "Clarke County",
    "Clarksville",
    "Clearwater",
    "Cleveland",
    "College Station",
    "Colorado Springs",
    "Columbia",
    "Columbus",
    "Concord",
    "Coral Springs",
    "Corona",
    "Corpus Christi",
    "Costa Mesa",
    "Dallas",
    "Daly City",
    "Danbury",
    "Davenport",
    "Davidson County",
    "Dayton",
    "Daytona Beach",
    "Deltona",
    "Denton",
    "Denver",
    "Des Moines",
    "Detroit",
    "Downey",
    "Duluth",
    "Durham",
    "El Monte",
    "El Paso",
    "Elizabeth",
    "Elk Grove",
    "Elkhart",
    "Erie",
    "Escondido",
    "Eugene",
    "Evansville",
    "Fairfield",
    "Fargo",
    "Fayetteville",
    "Fitchburg",
    "Flint",
    "Fontana",
    "Fort Collins",
    "Fort Lauderdale",
    "Fort Smith",
    "Fort Walton Beach",
    "Fort Wayne",
    "Fort Worth",
    "Frederick",
    "Fremont",
    "Fresno",
    "Fullerton",
    "Gainesville",
    "Garden Grove",
    "Garland",
    "Gastonia",
    "Gilbert",
    "Glendale",
    "Grand Prairie",
    "Grand Rapids",
    "Grayslake",
    "Green Bay",
    "GreenBay",
    "Greensboro",
    "Greenville",
    "Gulfport-Biloxi",
    "Hagerstown",
    "Hampton",
    "Harlingen",
    "Harrisburg",
    "Hartford",
    "Havre de Grace",
    "Hayward",
    "Hemet",
    "Henderson",
    "Hesperia",
    "Hialeah",
    "Hickory",
    "High Point",
    "Hollywood",
    "Honolulu",
    "Houma",
    "Houston",
    "Howell",
    "Huntington",
    "Huntington Beach",
    "Huntsville",
    "Independence",
    "Indianapolis",
    "Inglewood",
    "Irvine",
    "Irving",
    "Jackson",
    "Jacksonville",
    "Jefferson",
    "Jersey City",
    "Johnson City",
    "Joliet",
    "Kailua",
    "Kalamazoo",
    "Kaneohe",
    "Kansas City",
    "Kennewick",
    "Kenosha",
    "Killeen",
    "Kissimmee",
    "Knoxville",
    "Lacey",
    "Lafayette",
    "Lake Charles",
    "Lakeland",
    "Lakewood",
    "Lancaster",
    "Lansing",
    "Laredo",
    "Las Cruces",
    "Las Vegas",
    "Layton",
    "Leominster",
    "Lewisville",
    "Lexington",
    "Lincoln",
    "Little Rock",
    "Long Beach",
    "Lorain",
    "Los Angeles",
    "Louisville",
    "Lowell",
    "Lubbock",
    "Macon",
    "Madison",
    "Manchester",
    "Marina",
    "Marysville",
    "McAllen",
    "McHenry",
    "Medford",
    "Melbourne",
    "Memphis",
    "Merced",
    "Mesa",
    "Mesquite",
    "Miami",
    "Milwaukee",
    "Minneapolis",
    "Miramar",
    "Mission Viejo",
    "Mobile",
    "Modesto",
    "Monroe",
    "Monterey",
    "Montgomery",
    "Moreno Valley",
    "Murfreesboro",
    "Murrieta",
    "Muskegon",
    "Myrtle Beach",
    "Naperville",
    "Naples",
    "Nashua",
    "Nashville",
    "New Bedford",
    "New Haven",
    "New London",
    "New Orleans",
    "New York",
    "New York City",
    "Newark",
    "Newburgh",
    "Newport News",
    "Norfolk",
    "Normal",
    "Norman",
    "North Charleston",
    "North Las Vegas",
    "North Port",
    "Norwalk",
    "Norwich",
    "Oakland",
    "Ocala",
    "Oceanside",
    "Odessa",
    "Ogden",
    "Oklahoma City",
    "Olathe",
    "Olympia",
    "Omaha",
    "Ontario",
    "Orange",
    "Orem",
    "Orlando",
    "Overland Park",
    "Oxnard",
    "Palm Bay",
    "Palm Springs",
    "Palmdale",
    "Panama City",
    "Pasadena",
    "Paterson",
    "Pembroke Pines",
    "Pensacola",
    "Peoria",
    "Philadelphia",
    "Phoenix",
    "Pittsburgh",
    "Plano",
    "Pomona",
    "Pompano Beach",
    "Port Arthur",
    "Port Orange",
    "Port Saint Lucie",
    "Port St. Lucie",
    "Portland",
    "Portsmouth",
    "Poughkeepsie",
    "Providence",
    "Provo",
    "Pueblo",
    "Punta Gorda",
    "Racine",
    "Raleigh",
    "Rancho Cucamonga",
    "Reading",
    "Redding",
    "Reno",
    "Richland",
    "Richmond",
    "Richmond County",
    "Riverside",
    "Roanoke",
    "Rochester",
    "Rockford",
    "Roseville",
    "Round Lake Beach",
    "Sacramento",
    "Saginaw",
    "Saint Louis",
    "Saint Paul",
    "Saint Petersburg",
    "Salem",
    "Salinas",
    "Salt Lake City",
    "San Antonio",
    "San Bernardino",
    "San Buenaventura",
    "San Diego",
    "San Francisco",
    "San Jose",
    "Santa Ana",
    "Santa Barbara",
    "Santa Clara",
    "Santa Clarita",
    "Santa Cruz",
    "Santa Maria",
    "Santa Rosa",
    "Sarasota",
    "Savannah",
    "Scottsdale",
    "Scranton",
    "Seaside",
    "Seattle",
    "Sebastian",
    "Shreveport",
    "Simi Valley",
    "Sioux City",
    "Sioux Falls",
    "South Bend",
    "South Lyon",
    "Spartanburg",
    "Spokane",
    "Springdale",
    "Springfield",
    "St. Louis",
    "St. Paul",
    "St. Petersburg",
    "Stamford",
    "Sterling Heights",
    "Stockton",
    "Sunnyvale",
    "Syracuse",
    "Tacoma",
    "Tallahassee",
    "Tampa",
    "Temecula",
    "Tempe",
    "Thornton",
    "Thousand Oaks",
    "Toledo",
    "Topeka",
    "Torrance",
    "Trenton",
    "Tucson",
    "Tulsa",
    "Tuscaloosa",
    "Tyler",
    "Utica",
    "Vallejo",
    "Vancouver",
    "Vero Beach",
    "Victorville",
    "Virginia Beach",
    "Visalia",
    "Waco",
    "Warren",
    "Washington",
    "Waterbury",
    "Waterloo",
    "West Covina",
    "West Valley City",
    "Westminster",
    "Wichita",
    "Wilmington",
    "Winston",
    "Winter Haven",
    "Worcester",
    "Yakima",
    "Yonkers",
    "York",
    "Youngstown",
  ];
  
  const countryNames = [
    "Afghanistan",
    "Albania",
    "Algeria",
    "Andorra",
    "Angola",
    "Anguilla",
    "Antigua &amp; Barbuda",
    "Argentina",
    "Armenia",
    "Aruba",
    "Australia",
    "Austria",
    "Azerbaijan",
    "Bahamas",
    "Bahrain",
    "Bangladesh",
    "Barbados",
    "Belarus",
    "Belgium",
    "Belize",
    "Benin",
    "Bermuda",
    "Bhutan",
    "Bolivia",
    "Bosnia &amp; Herzegovina",
    "Botswana",
    "Brazil",
    "British Virgin Islands",
    "Brunei",
    "Bulgaria",
    "Burkina Faso",
    "Burundi",
    "Cambodia",
    "Cameroon",
    "Canada",
    "Cape Verde",
    "Cayman Islands",
    "Chad",
    "Chile",
    "China",
    "Colombia",
    "Congo",
    "Cook Islands",
    "Costa Rica",
    "Cote D Ivoire",
    "Croatia",
    "Cruise Ship",
    "Cuba",
    "Cyprus",
    "Czech Republic",
    "Denmark",
    "Djibouti",
    "Dominica",
    "Dominican Republic",
    "Ecuador",
    "Egypt",
    "El Salvador",
    "Equatorial Guinea",
    "Estonia",
    "Ethiopia",
    "Falkland Islands",
    "Faroe Islands",
    "Fiji",
    "Finland",
    "France",
    "French Polynesia",
    "French West Indies",
    "Gabon",
    "Gambia",
    "Georgia",
    "Germany",
    "Ghana",
    "Gibraltar",
    "Greece",
    "Greenland",
    "Grenada",
    "Guam",
    "Guatemala",
    "Guernsey",
    "Guinea",
    "Guinea Bissau",
    "Guyana",
    "Haiti",
    "Honduras",
    "Hong Kong",
    "Hungary",
    "Iceland",
    "India",
    "Indonesia",
    "Iran",
    "Iraq",
    "Ireland",
    "Isle of Man",
    "Israel",
    "Italy",
    "Jamaica",
    "Japan",
    "Jersey",
    "Jordan",
    "Kazakhstan",
    "Kenya",
    "Kuwait",
    "Kyrgyz Republic",
    "Laos",
    "Latvia",
    "Lebanon",
    "Lesotho",
    "Liberia",
    "Libya",
    "Liechtenstein",
    "Lithuania",
    "Luxembourg",
    "Macau",
    "Macedonia",
    "Madagascar",
    "Malawi",
    "Malaysia",
    "Maldives",
    "Mali",
    "Malta",
    "Mauritania",
    "Mauritius",
    "Mexico",
    "Moldova",
    "Monaco",
    "Mongolia",
    "Montenegro",
    "Montserrat",
    "Morocco",
    "Mozambique",
    "Namibia",
    "Nepal",
    "Netherlands",
    "Netherlands Antilles",
    "New Caledonia",
    "New Zealand",
    "Nicaragua",
    "Niger",
    "Nigeria",
    "Norway",
    "Oman",
    "Pakistan",
    "Palestine",
    "Panama",
    "Papua New Guinea",
    "Paraguay",
    "Peru",
    "Philippines",
    "Poland",
    "Portugal",
    "Puerto Rico",
    "Qatar",
    "Reunion",
    "Romania",
    "Russia",
    "Rwanda",
    "Saint Pierre &amp; Miquelon",
    "Samoa",
    "San Marino",
    "Satellite",
    "Saudi Arabia",
    "Senegal",
    "Serbia",
    "Seychelles",
    "Sierra Leone",
    "Singapore",
    "Slovakia",
    "Slovenia",
    "South Africa",
    "South Korea",
    "Spain",
    "Sri Lanka",
    "St Kitts &amp; Nevis",
    "St Lucia",
    "St Vincent",
    "St. Lucia",
    "Sudan",
    "Suriname",
    "Swaziland",
    "Sweden",
    "Switzerland",
    "Syria",
    "Taiwan",
    "Tajikistan",
    "Tanzania",
    "Thailand",
    "Timor L'Este",
    "Togo",
    "Tonga",
    "Trinidad &amp; Tobago",
    "Tunisia",
    "Turkey",
    "Turkmenistan",
    "Turks &amp; Caicos",
    "Uganda",
    "Ukraine",
    "United Arab Emirates",
    "United Kingdom",
    "United States of America",
    "Uruguay",
    "Uzbekistan",
    "Venezuela",
    "Vietnam",
    "Virgin Islands (US)",
    "Yemen",
    "Zambia",
    "Zimbabwe",
  ];
  const usStates = [
    "Alabama",
    "Alaska",
    "American Samoa",
    "Arizona",
    "Arkansas",
    "California",
    "Colorado",
    "Connecticut",
    "Delaware",
    "District of Columbia",
    "Federated States of Micronesia",
    "Florida",
    "Georgia",
    "Guam",
    "Hawaii",
    "Idaho",
    "Illinois",
    "Indiana",
    "Iowa",
    "Kansas",
    "Kentucky",
    "Louisiana",
    "Maine",
    "Marshall Islands",
    "Maryland",
    "Massachusetts",
    "Michigan",
    "Minnesota",
    "Mississippi",
    "Missouri",
    "Montana",
    "Nebraska",
    "Nevada",
    "New Hampshire",
    "New Jersey",
    "New Mexico",
    "New York",
    "North Carolina",
    "North Dakota",
    "Northern Mariana Islands",
    "Ohio",
    "Oklahoma",
    "Oregon",
    "Palau",
    "Pennsylvania",
    "Puerto Rico",
    "Rhode Island",
    "South Carolina",
    "South Dakota",
    "Tennessee",
    "Texas",
    "Utah",
    "Vermont",
    "Virgin Island",
    "Virginia",
    "Washington",
    "West Virginia",
    "Wisconsin",
    "Wyoming",
  ];
  const months = [
    "January",
    "February",
    "March",
    "April",
    "May",
    "June",
    "July",
    "August",
    "September",
    "October",
    "November",
    "December",
  ];
  const years = ["2022", "2023", "2024", "2025", "2026", "47 A.D"];
  const nameAdressArr = [
    {
      label: "Address Title",
      name: "addressTitle",
      type: "text",
    },
    {
      label: "Name-Surname",
      name: "nameSurName",
      type: "text",
    },
    {
      label: "Your Address",
      name: "yourAddress",
      type: "text",
    },
  ];
  
  const addressDetails = [
    {
      label: "Country",
      name: "country",
      type: "select",
      selectionArray: countryNames,
    },
    {
      label: "City",
      name: "city",
      type: "select",
      selectionArray: cityNames,
    },
    {
      label: "State",
      name: "usState",
      type: "select",
      selectionArray: usStates,
    },
  ];
  const phoneNumbers = [
    {
      label: "Cell Phone",
      name: "cellPhone",
      type: "text",
    },
    {
      label: "Telephone",
      name: "telephone",
      type: "text",
    },
  ];
  export {
    usStates,
    countryNames,
    cityNames,
    months,
    years,
    phoneNumbers,
    nameAdressArr,
    addressDetails,
  };
  
  export const OTHERCARDS = [
    /[1-9]/,
    /\d/,
    /\d/,
    /\d/,
    " ",
    /\d/,
    /\d/,
    /\d/,
    /\d/,
    " ",
    /\d/,
    /\d/,
    /\d/,
    /\d/,
    " ",
    /\d/,
    /\d/,
    /\d/,
    /\d/,
  ];
  
  export const AMERICAN_EXPRESS = [
    /[1-9]/,
    /\d/,
    /\d/,
    /\d/,
    " ",
    /\d/,
    /\d/,
    /\d/,
    /\d/,
    /\d/,
    /\d/,
    " ",
    /\d/,
    /\d/,
    /\d/,
    /\d/,
    /\d/,
  ];
  
  export const CARD = ["VISA", "MASTERCARD", "AMERICAN_EXPRESS", "DISCOVER"];
  
  